class LcdError(Exception): ...


class LcdNotConnectedError(LcdError): ...


class LcdNotInitializedError(LcdError): ...


class LcdInvalidParameterError(LcdError): ...


class LcdInvalidCommandError(LcdError): ...


class LcdInvalidImageError(LcdError): ...
